config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }


  resources :heroes do
    resources :candles, only: [:create]
    resources :notes, only: [:create]
  end

  root 'heroes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/hero.rb
class Hero < ApplicationRecord
  belongs_to :created_by, class_name: 'User', foreign_key: 'created_by_id'

  validates :name, presence: true
  validates :image, presence: true

  has_one_attached :image

  before_validation :set_default_image, if: -> { image.blank? }
  after_create :add_initial_candle

  private

  def set_default_image
    self.image.attach(io: File.open(Rails.root.join('app/assets/images/flowers.png')), filename: 'flowers.png') if image.blank?
  end

  def add_initial_candle
    update(candles: 1)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :heroes, foreign_key: 'created_by_id'
  # has_many :candles
  # has_many :notes

  enum role: { user: 0, admin: 1 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
  format: { with: VALID_EMAIL_REGEX },
  uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index

  end
end

app/controllers/candles_controller.rb
class CandlesController < ApplicationController
  before_action :set_hero

  def create
    @candle = @hero.candles.build
    if @candle.save
      redirect_to @hero, notice: 'Candle was successfully lit.'
    else
      redirect_to @hero, alert: 'Failed to light candle.'
    end
  end

  private

  def set_hero
    @hero = Hero.find(params[:hero_id])
  end
end

app/controllers/heroes_controller.rb
class HeroesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :increase_candle_count]
  before_action :set_hero, only: [:show, :edit, :update, :destroy, :increase_candle_count, :add_note]

  def index
    @heroes = Hero.all
  end

  def show
    @notes = @hero.notes.order(created_at: :desc)
  end

  def increase_candle_count
    @hero.candles.create!
    redirect_to @hero
  end

  def add_note
    @hero.notes.create!(content: params[:note], created_by: current_user)
    redirect_to @hero
  end

  def new
    @hero = Hero.new
  end

  def create
    @hero = current_user.heroes.build(hero_params)
    @hero.image.attach(params[:hero][:image])
    if @hero.save
      redirect_to @hero, notice: 'Hero was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @hero.update(hero_params)
      redirect_to @hero, notice: 'Hero was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @hero.destroy
    redirect_to heroes_url, notice: 'Hero was successfully deleted.'
  end

  private

  def set_hero
    @hero = Hero.find(params[:id])
  end

  def hero_params
    params.require(:hero).permit(:name, :image, :note)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def create
    @dead_person = Hero.find(params[:hero_id])
    @note = @hero.notes.build(note_params)
    @note.user = current_user
    if @note.save
      redirect_to @hero, notice: 'Note was successfully added.'
    else
      redirect_to @hero, alert: 'Failed to add note.'
    end
  end

  private

  def note_params
    params.require(:note).permit(:content)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  def new
    super
  end

  # POST /resource/password
  def create
    super
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  # PUT /resource/password
  def update
    super
  end

  protected

  def after_resetting_password_path_for(resource)
    super(resource)
  end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    super(resource_name)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Light Me A Candle"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/candles_helper.rb
module CandlesHelper
end

app/helpers/heroes_helper.rb
module HeroesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/heroes/_form.html.erb
<%= form_with(model: hero, local: true, html: { class: "needs-validation", novalidate: true }) do |form| %>
  <% if hero.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h4 class="alert-heading"><%= pluralize(hero.errors.count, "error") %> prohibited this hero from being saved:</h4>
      <ul>
        <% hero.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control", required: true %>
    <div class="invalid-feedback">
      Please provide a name.
    </div>
  </div>

  <div class="mb-3">
    <%= form.label :image, class: "form-label" %>
    <%= form.file_field :image, class: "form-control" %>
    <div class="invalid-feedback">
      Please provide a valid image.
    </div>
  </div>

  <div class="mb-3">
    <%= form.label :note, class: "form-label" %>
    <%= form.text_area :note, class: "form-control" %>
  </div>

  <div class="d-grid">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

<script>
  // JavaScript for disabling form submissions if there are invalid fields
  (function () {
    'use strict';
    window.addEventListener('load', function () {
      var forms = document.getElementsByClassName('needs-validation');
      Array.prototype.filter.call(forms, function (form) {
        form.addEventListener('submit', function (event) {
          if (form.checkValidity() === false) {
            event.preventDefault();
            event.stopPropagation();
          }
          form.classList.add('was-validated');
        }, false);
      });
    }, false);
  })();
</script>

app/views/heroes/create.html.erb
<h1>Heroes#create</h1>
<p>Find me in app/views/heroes/create.html.erb</p>

app/views/heroes/destroy.html.erb
<h1>Heroes#destroy</h1>
<p>Find me in app/views/heroes/destroy.html.erb</p>

app/views/heroes/edit.html.erb
<h1>Heroes#edit</h1>
<p>Find me in app/views/heroes/edit.html.erb</p>

app/views/heroes/index.html.erb
<div class="burning-candles">
    <div class="row">
        <div class="col-12 py-4">
            <%= image_tag 'candles-for-me.gif', class: 'img-fluid rounded', alt: 'Responsive GIF' %>
        </div>

        <div class="">
            <%= link_to new_hero_path, class: "btn btn-primary mb-3" do %>
                <i class="bi bi-plus-square-fill"></i> Add New Hero
            <% end %>
        </div>

    </div>
</div>

app/views/heroes/new.html.erb
<%= form_for(@hero, url: heroes_path, html: { class: "needs-validation", novalidate: true }) do |form| %>
  <% if @hero.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h4 class="alert-heading"><%= pluralize(@hero.errors.count, "error") %> prohibited this hero from being saved:</h4>
      <ul>
        <% @hero.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control", required: true %>
    <div class="invalid-feedback">
      Please provide a name.
    </div>
  </div>

  <div class="mb-3">
    <%= form.label :image, class: "form-label" %>
    <%= form.file_field :image, class: "form-control" %>
    <div class="invalid-feedback">
      Please provide a valid image.
    </div>
  </div>

  <div class="mb-3">
    <%= form.label :notes, class: "form-label" %>
    <%= form.text_area :notes, class: "form-control" %>
  </div>

  <div class="d-grid">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

<script>
  // JavaScript for disabling form submissions if there are invalid fields
  (function () {
    'use strict';
    window.addEventListener('load', function () {
      var forms = document.getElementsByClassName('needs-validation');
      Array.prototype.filter.call(forms, function (form) {
        form.addEventListener('submit', function (event) {
          if (form.checkValidity() === false) {
            event.preventDefault();
            event.stopPropagation();
          }
          form.classList.add('was-validated');
        }, false);
      });
    }, false);
  })();
</script>

app/views/heroes/show.html.erb
<!-- app/views/heroes/show.html.erb -->
<div class="container">
  <div class="row">
    <div class="col-12 text-center my-4">
      <h1><%= @hero.name %></h1>
      <p><%= @hero.note %></p>
      <%= button_to 'Candle Count: ' + @hero.candles.count.to_s, hero_candles_path(@hero), method: :post, class: "btn btn-primary" %>
    </div>
  </div>

  <div class="row">
    <div class="col-12 text-center">
      <%= image_tag @hero.image.attached? ? url_for(@hero.image) : asset_path('flowers.png'), class: 'img-fluid' %>
    </div>
  </div>

  <div class="row my-4">
    <div class="col-12">
      <h2>Notes</h2>
      <div id="notesCarousel" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <% @notes.each_with_index do |note, index| %>
            <div class="carousel-item <%= 'active' if index.zero? %>">
              <div class="d-block w-100 p-4">
                <p><%= note.content %></p>
                <p><small>Added by <%= note.created_by.email %> at <%= note.created_at.strftime('%Y-%m-%d %H:%M:%S') %></small></p>
              </div>
            </div>
          <% end %>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#notesCarousel" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#notesCarousel" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    </div>
  </div>

  <% if user_signed_in? %>
    <div class="row my-4">
      <div class="col-12">
        <h2>Add a Note</h2>
        <%= form_with url: hero_notes_path(@hero), method: :post, local: true do |form| %>
          <div class="mb-3">
            <%= form.text_area :note, class: "form-control", rows: 3, placeholder: "Write your note here..." %>
          </div>
          <%= form.submit 'Add Note', class: "btn btn-success" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/heroes/update.html.erb
<h1>Heroes#update</h1>
<p>Find me in app/views/heroes/update.html.erb</p>

app/views/layouts/_footer.html.erb
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="github" viewBox="0 0 16 16">
    <title>GitHub</title>
    <path fill-rule="evenodd" clip-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.58.82-2.13-.08-.2-.36-1.02.08-2.12 0 0 .67-.22 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.55.82 1.26.82 2.13 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.002 8.002 0 0016 8c0-4.42-3.58-8-8-8z"></path>
  </symbol>
  <symbol id="facebook" viewBox="0 0 16 16">
    <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
  </symbol>
  <symbol id="instagram" viewBox="0 0 16 16">
      <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
  </symbol>
  <symbol id="twitter" viewBox="0 0 16 16">
    <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
  </symbol>
</svg>

<div class="container">
  <footer class="justify-content-between align-items-center py-3 my-4 border-top">
    <ul class="nav justify-content-center list-unstyled d-flex">
      <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"/></svg></a></li>
      <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"/></svg></a></li>
      <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"/></svg></a></li>
      <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#github"/></svg></a></li>
    </ul>
  </footer>
</div>

<div class="container">
  <footer class="justify-content-between align-items-center py-3 my-4 border-top">
    <ul class="nav justify-content-center list-unstyled d-flex">
      <%= link_to image_tag("light.svg", alt: "Logo", width: "80"), root_path %>
    </ul>
  </footer>
</div>

<div class="container">
  <footer>
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li><%= link_to "About",   "#", class: "nav-item nav-link px-2 text-muted" %></li>
      <li class="nav-item"><a href="https://suuef.com/blog" class="nav-link px-2 text-muted">News</a></li>
    </ul>

    <p class="text-center text-muted">
      Light Me A Candle &copy; 2024. All rights reserved.
    </p>
  </footer>
</div>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light py-4">
    <div class="container">
      <%= link_to "Light Me A Candle", root_path, class: "navbar-brand fw-bold", id: "logo" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li><%= link_to "Home", root_path, class: "nav-item nav-link active ms-0 ms-md-3", "aria-current": "page" %></li>
          <li><%= link_to "About", "#", class: "nav-item nav-link", "aria-current": "page" %></li>

          <% if user_signed_in? %>
            <li><%= link_to "Add A Hero", "#", class: "nav-item nav-link ms-0 ms-md-3", "aria-current": "page" %></li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Account
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><%= link_to "Profile", "#", class: "dropdown-item" %></li>
                <li><%= link_to "Settings", "#", class: "dropdown-item" %></li>
                <li><hr class="dropdown-divider"></li>
                <li><%= link_to "Log out", destroy_user_session_path, method: :delete, data: { "turbo-method": :delete }, class: "dropdown-item" %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Log in", new_user_session_path, class: "nav-item nav-link ms-0 ms-md-3" %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.0/font/bootstrap-icons.min.css', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <% bootstrap_class = case message_type %>
          <% when 'notice' then 'success' %>
          <% when 'alert' then 'danger' %>
          <% else message_type %>
        <% end %>
        <div class="alert alert-<%= bootstrap_class %>">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" class="alert alert-danger" role="alert" data-turbo-cache="false">
    <h4 class="alert-heading">
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h4>
    <ul class="mb-0">
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: "text-decoration-none mb-2 d-block" %>
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: "text-decoration-none mt-2 mb-2 d-block" %>
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), class: "text-decoration-none mb-2 d-block" %>
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name), class: "text-decoration-none mb-2 d-block" %>
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name), class: "text-decoration-none mb-2 d-block" %>
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), class: "btn btn-outline-primary mb-2", data: { turbo: false } %><br />
  <% end %>
<% end %>